{{- if .Values.forgotpassword.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skygear.forgotpassword.name" . | quote }}
  labels:
    {{- include "skygear.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "skygear.labels" . | nindent 4 }}
    app: {{ include "skygear.forgotpassword.name" . | quote }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skygear.forgotpassword.name" . | quote }}
  labels:
    {{- include "skygear.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.forgotpassword.replicas }}
  selector:
    matchLabels:
      app: {{ include "skygear.forgotpassword.name" . | quote }}
  template:
    metadata:
      labels:
        {{- include "skygear.labels" . | nindent 8 }}
        app: {{ include "skygear.forgotpassword.name" . | quote }}
    spec:
      {{- if .Values.forgotpassword.configMapName }}
      volumes:
      - name: templates
        configMap:
          name: {{ .Values.forgotpassword.configMapName | quote }}
      {{- end }}
      containers:
      - name: forgotpassword
        image: {{ .Values.forgotpassword.image | quote }}
        ports:
        - protocol: TCP
          containerPort: 5000
        {{- if .Values.forgotpassword.configMapName }}
        volumeMounts:
        - name: templates
          mountPath: /usr/src/app/templates/forgot_password
        {{- end }}
        env:
        {{- include "skygear.common.env-vars" . | nindent 8 }}
        {{- include "skygear.plugin.env-vars" . | nindent 8 }}
        - name: HTTP_ADDR
          value: "0.0.0.0:5000"
        - name: SKYGEAR_ADDRESS
          value: tcp://{{ include "skygear.skygear-server.name" . }}:5000
        - name: FORGOT_PASSWORD_URL_PREFIX
          value: https://{{ .Values.publicHost }}
        - name: SMTP_HOST
          value: {{ .Values.forgotpassword.smtp.host | quote }}
        - name: SMTP_PORT
          value: {{ .Values.forgotpassword.smtp.port | quote }}
        - name: SMTP_MODE
          value: {{ .Values.forgotpassword.smtp.mode | quote }}
        - name: SMTP_LOGIN
          value: {{ .Values.forgotpassword.smtp.login | quote }}
        - name: SMTP_PASSWORD
          value: {{ .Values.forgotpassword.smtp.password | quote }}
        {{- if .Values.forgotpassword.env }}
        {{- toYaml .Values.forgotpassword.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.forgotpassword.resources | nindent 10 }}
{{- end }}
