{{- if .Values.pluginnodejs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skygear.pluginnodejs.name" . | quote }}
  labels:
    {{- include "skygear.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "skygear.labels" . | nindent 4 }}
    app: {{ include "skygear.pluginnodejs.name" . | quote }}
  ports:
  - protocol: TCP
    port: 5004
    targetPort: 5004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skygear.pluginnodejs.name" . | quote }}
  labels:
    {{- include "skygear.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pluginnodejs.replicas }}
  selector:
    matchLabels:
      app: {{ include "skygear.pluginnodejs.name" . | quote }}
  template:
    metadata:
      labels:
        {{- include "skygear.labels" . | nindent 8 }}
        app: {{ include "skygear.pluginnodejs.name" . | quote }}
    spec:
      containers:
      - name: pluginnodejs
        image: {{ .Values.pluginnodejs.image | quote }}
        ports:
        - protocol: TCP
          containerPort: 5004
        env:
        {{- include "skygear.common.env-vars" . | nindent 8 }}
        {{- include "skygear.plugin.env-vars" . | nindent 8 }}
        - name: HTTP_ADDR
          value: "0.0.0.0:5004"
        - name: SKYGEAR_ADDRESS
          value: tcp://{{ include "skygear.skygear-server.name" . }}:5004
        {{- if .Values.pluginnodejs.env }}
        {{- toYaml .Values.pluginnodejs.env | nindent 8 }}
        {{- end }}
        {{- if (or .Values.pluginnodejs.envFromConfigMapName .Values.pluginnodejs.envFromSecretName) }}
        envFrom:
        {{- if .Values.pluginnodejs.envFromConfigMapName }}
        - configMapRef:
            name: {{ .Values.pluginnodejs.envFromConfigMapName | quote }}
        {{- end }}
        {{- if .Values.pluginnodejs.envFromSecretName }}
        - secretRef:
            name: {{ .Values.pluginnodejs.envFromSecretName | quote }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.pluginnodejs.resources | nindent 10 }}
{{- end }}
